var greet = "Hello";
var name = "Zain";
console.log(greet.charAt(0));
console.log(greet.length);
console.log(greet.concat(name));
console.log(greet.indexOf("l"));
console.log(greet.lastIndexOf("l"));
console.log(greet.split("e"));
console.log("Hello,World".split(","));
console.log(greet.toUpperCase());
console.log(greet.toLowerCase());
